from .cats.list import cat_list
from .caretakers.list import caretaker_list
from .kennels.list import kennel_list
from .home import home
from .auth.logout import logout_user
from .cats.form import cat_form
from .kennels.form import kennel_form
from .cats.details import cat_details
from .kennels.details import kennel_details
from .caretakers.details import caretaker_details
from .cats.form import cat_edit_form